FILTER_OUT = ["advanced with headsets",
              "advanced (min 30 classes) with headsets",
              "advanced class with headsets",
              "advanced with headsets",
              "advanced workout with headsets",
              "advanced with headsets (min 30 classes)",
              "all reformer - begin",
              "all reformer - bridge",
              "all reformer - elevate",
              "all reformer - jump",
              "ass & abs with headsets",
              "ass & abs class with headsets",
              "ass and abs with headsets",
              "ass and abs class with headsets",
              "ass and abs workout with headsets",
              "beginners class with headsets",
              "booty + abs",
              "booty + core",
              "breathwork | one-on-one session",
              "charge x (hybrid strength + cardio)",
              "define x (strength full body)",
              "full body class with headsets",
              "full body workout with headsets",
              "full body with headsets",
              "foundation ( pilates + balance + core )",
              "foundation (pilates + balance + core)",
              "Happy Hour Mega Cardio Xpress- Arms/Abs+Tread (45)"
              "haus party - megaformer fullbody",
              "hiit + heavy",
              "hustle x",
              "infrared lagree - arms + core",
              "infrared lagree - legs + core",
              "infrared lagree - stretch + reset",
              "infrared lagree - full body",
              "intermediate (min 10 classes) with headsets",
              "lagree - arms + core",
              "lagree - full body",
              "lagree - fundamentals",
              "lagree - legs + core",
              "mat werk + weights",
              "mcx - ass/abs+tread",
              "mcx-arms/abs+tread",
              "mega cardio xpress",
              "mega cardio xpress- ass/abs+tread (45 min)",
              "mega cardio xpress- ass/abs+tread (45)",
              "mega cardio xpress- arms/abs+tread (45 min)",
              "mega cardio xpress- arms/abs+tread (45)",
              "mega cardio- arms/abs+tread",
              "mega cardio- arms/abs+tread (55 min)",
              "mega cardio- ass/abs+tread (55 min)",
              "megaformer ass + abs",
              "megaformer arms + abs",
              "megaformer strength + stretch",
              "megaformer strength + stretch (45 min)",
              "megaformer x flashback fridays",
              "megaformer + stretch",
              "meta + mat werk 45",
              "meta + mat werk 60 min",
              "meta + weights 45",
              "meta x mn",
              "pilates | foundation | strength + core (heated)",
              "postpartum +baby: control + core",
              "postpartum +baby: strength",
              "prenatal pilates + core",
              "reiki | one-on-one session",
              "ritual sound journey (relax and unwind)",
              "sculpt x (strength lower body + core)",
              "slow flow + sound",
              "slow flow vinyasa + sound",
              "sound journey | tea + journaling",
              "sweatcon",
              "sweatcon arms + abs",
              "the balance + breathwork",
              "the balance + sound bath",
              "the balance x all is well",
              "the balance —",
              "the bird —",
              "the booty — reformer",
              "the burn | arms + abs —",
              "the burn | arms + abs — reformer —",
              "the burn | arms + abs — reformer (heated) — hh",
              "the burn — reformer (heated)",
              "the burn — reformer (heated) —",
              "the burn — reformer",
              "the burn — reformer —",
              "the build —",
              "the build -",
              "the burn —",
              "the impact (boxing technique & strength)",
              "the remix (rhythmic boxing & endurance)",
              "theme: rise + rave",
              "trx strength",
              "thrive (pilates + sculpt + light cardio)",
              "upper body + abs",
              "vinyasa slow flow yoga + sound",
              "warm yin + aromatherapy",
              "warm yin yoga + aromatherapy",
              "yin yoga + aromatherapy",
              "yoga | yin + aromatherapy",
              "yoga | candlelight yin + sound (warm)",
              "yoga | flow + breath (warm)",
              "yoga | flow + yin (heated)",
              "yoga | yin + breath (warm)"
              ]