FILTER_OUT = ["advanced with headsets",
              "advanced (min 30 classes) with headsets",
              "advanced class with headsets",
              "advanced with headsets",
              "advanced workout with headsets",
              "advanced with headsets (min 30 classes)",
              "all lift at the set - private booking",
              "all reformer - begin",
              "all reformer - bridge",
              "all reformer - elevate",
              "all reformer - jump",
              "ass & abs with headsets",
              "ass & abs class with headsets",
              "ass and abs with headsets",
              "ass and abs class with headsets",
              "ass and abs workout with headsets",
              "beginners class with headsets",
              "booty + abs",
              "booty + core",
              "breathwork | one-on-one session",
              "breathwork + sound bath | warm",
              "breathwork + sound bath",
              "charge x (hybrid strength + cardio)",
              "cosmic gong bath - 40 min",
              "define x (strength full body)",
              "flow state | warm - full moon",
              "full moon sound bath - 40 min",
              "full moon sound bath - 40 min | warm",
              "full body class with headsets",
              "full body workout with headsets",
              "full body with headsets",
              "foundation ( pilates + balance + core )",
              "foundation (pilates + balance + core)",
              "foundation | strength + core (heated)",
              "haus party - megaformer fullbody",
              "hiit + heavy",
              "hustle x",
              "infrared lagree - arms + core",
              "infrared lagree - legs + core",
              "infrared lagree - stretch + reset",
              "infrared lagree - full body",
              "inquiry + sound bath w/ integration- full moon",
              "intermediate (min 10 classes) with headsets",
              "lagree - arms + core",
              "lagree - full body",
              "lagree - fundamentals",
              "lagree - legs + core",
              "mat werk + weights",
              "mcx - ass/abs+tread",
              "mcx-arms/abs+tread",
              "mega cardio xpress",
              "mega cardio xpress- ass/abs+tread (45 min)",
              "mega cardio xpress- ass/abs+tread (45)",
              "mega cardio xpress- arms/abs+tread (45 min)",
              "mega cardio xpress- arms/abs+tread (45)",
              "mega cardio- arms/abs+tread",
              "mega cardio- arms/abs+tread (55 min)",
              "mega cardio- ass/abs+tread (55 min)",
              "megaformer ass + abs",
              "megaformer arms + abs",
              "megaformer strength + stretch",
              "megaformer strength + stretch (45 min)",
              "megaformer x flashback fridays",
              "megaformer x flashback friday",
              "megaformer + stretch",
              "meta + mat werk 45",
              "meta + mat werk 60 min",
              "meta + weights",
              "meta + weights 45",
              "meta x mn",
              "mrc x turf free run club (no sign up needed)",
              "on the mat with nat *happy hour 🐜*",
              "pilates | foundation | strength + core (heated)",
              "pilates sweat | hot",
              "postpartum +baby: control + core",
              "postpartum +baby: strength",
              "power yoga + sound bath | hot",
              "prenatal pilates + core",
              "red light reiki + sound for sleep",
              "red light yin + sound bath",
              "reiki infused sound bath w/ scent + integration",
              "reiki infused sound bath w/ scent - 40 min",
              "reiki infused sound bath w/ scent | warm - 40 min",
              "reiki infused sound bath w/ scent | warm - 40 mins",
              "reiki infused sound bath | red light - 40 min",
              "reiki | one-on-one session",
              "ritual sound journey (relax and unwind)",
              "sculpt x (strength lower body + core)",
              "self inquiry + sound bath w/ integration",
              "slow flow + sound",
              "slow flow vinyasa + sound",
              "sound journey | tea + journaling",
              "sweatcon",
              "sweatcon arms + abs",
              "symphony sound bath - 40 mins",
              "symphony sound bath | warm - 40 mins",
              "the balance + breathwork",
              "the balance + sound bath",
              "the balance x all is well",
              "the balance —",
              "the bird —",
              "the booty — reformer",
              "the burn | arms + abs —",
              "the burn | arms + abs — reformer —",
              "the burn | arms + abs — reformer (heated) — hh",
              "the burn — reformer (heated)",
              "the burn — reformer (heated) —",
              "the burn — reformer",
              "the burn — reformer —",
              "the build —",
              "the build -",
              "the burn —",
              "the impact (boxing technique & strength)",
              "the remix (rhythmic boxing & endurance)",
              "theme: rise + rave",
              "trx strength",
              "thrive (pilates + sculpt + light cardio)",
              "upper body + abs",
              "vinyasa slow flow yoga + sound",
              "vinyasa flow + sound bath",
              "vinyasa flow + sound bath | hot",
              "vinyasa flow + sound bath | warm",
              "warm yin + aromatherapy",
              "warm yin yoga + aromatherapy",
              "yin yoga + aromatherapy",
              "yin + sound bath",
              "yoga | yin + aromatherapy",
              "yoga | yin + aromatherapy (warm)",
              "yoga | candlelight yin + sound (warm)",
              "yoga | flow + breath (warm)",
              "yoga | flow + yin (heated)",
              "yoga | restorative + breath (warm)",
              "yoga | yin + breath (warm)",
              "yoga | yin + sound (warm)"
              ]
