FILTER_OUT = {
    "all method studio": [
        "all lift at the set - private booking",
        "all reformer - begin",
        "all reformer - begin happy hour 55 mins",
        "all reformer - bridge",
        "all reformer - elevate",
        "all reformer - jump",
        "all reformer - jump happy hour 55 mins",
    ],
    "evolution": [
        "define x (strength full body)",
        "infrared lagree - arms + core",
        "infrared lagree - full body",
        "infrared lagree - legs + core",
        "infrared lagree - themed",
        "lagree - fundamentals",
        "lagree - full body",
        "sculpt x (strength lower body + core)",
        "the remix (rhythmic boxing & endurance)",
    ],
    "hustle": [
        "trx strength",
        "hiit + heavy",
        "booty + core",
        "postpartum +baby: strength",
        "hustle x",
        "postpartum +baby: control + core",
        "sweatcon arms + abs",
        "prenatal pilates + core",
        "yoga + mobility",
    ],
    "jaybird": [
        "the balance + sound bath",
        "the balance x all is well",
        "the booty — reformer",
        "the burn — reformer",
        "the burn — reformer (heated)",
        "the burn | arms + abs",
        "the burn | arms + abs — reformer (heated) — hh",
        "the burn | arms + abs — reformer",
    ],
    "lagree pulse": [
        "booty + abs",
        "upper body + abs",
    ],
    "lagree studio": [
        "advanced (min 30 classes) with headsets",
        "ass & abs with headsets",
        "ass and abs with headsets",
        "full body",
        "full body with headsets",
        "full body workout with headsets",
        "intermediate (min 10 classes)",
    ],
    "lagree west": [
        "mega cardio xpress- arms/abs+tread (45 min)",
        "mega cardio xpress- arms/abs+tread (45)",
        "mega cardio- arms/abs+tread (55 min)",
        "mega cardio xpress- ass/abs+tread (45 min)",
        "mega x hips dont lie, glutes will cry",
        "megaformer arms + abs",
        "megaformer ass + abs",
        "megaformer strength + stretch (45 min)",
        "megaformer x flashback friday",
        "megaformer x flashback fridays",
        "megaformer x house music fridays",
        "megaformer x booty goals",
    ],
    "lagree x":[
        "megapro full body",
    ],
    "turf": [
        "mat werk + weights",
        "meta + mat werk 45",
        "meta + mat werk 60 min",
        "meta x mn",
        "meta + weights",
        "meta + weights 45",
        "on the mat with nat *happy hour \ud83d\udc1c*",
        "on the mat with nat *happy hour 🐜*",
        "mrc x turf free run club (no sign up needed)",
    ],
    "ritual": [
        "foundation | stability + core",
        "foundation | stability + core (heated)",
        "foundation | strength + cardio",
        "foundation | strength + core (heated)",
        "pilates | foundation | strength + core (heated)",
        "sound journey | tea + journaling",
        "yoga | candlelight yin + sound (warm)",
        "yoga | flow + breath (warm)",
        "yoga | flow + yin (heated)",
        "yoga | restorative + breath (warm)",
        "yoga | yin + aromatherapy (warm)",
        "yoga | yin + breath (warm)",

    ],
    "zenden": [
        "breathwork + sound bath",
        "cosmic gong bath - 40 min",
        "crystal sound bath for sleep",
        "pilates sculpt | hot - arms + abs",
        "pilates sculpt | hot - arms + abs",
        "pilates sculpt | hot - lower body",
        "pilates sculpt | red light - arms + abs",
        "pilates sculpt | red light - arms & abs",
        "pilates sculpt | red light - lower body",
        "pilates sweat | hot",
        "pilates sculpt | warm - arms + abs",
        "power yoga + sound bath | hot",
        "red light reiki + sound for sleep",
        "red light yin + sound bath",
        "reiki infused sound bath | red light - 40 min",
        "reiki infused sound bath w/ scent + integration",
        "self inquiry + sound bath w/ integration",
        "vinyasa flow + sound bath",
        "vinyasa flow + sound bath | warm",
        "vinyasa flow + sound bath | hot",
        "yin + sound bath",
        "yin + sound bath | warm",
    ],
}
